_BASE_: "Base-Panoptic-FPN.yaml"
MODEL:
  WEIGHTS: "R-50.pkl"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
  SEM_SEG_HEAD:
    IGNORE_VALUE: 255
SOLVER:
  OPTIMIZER: "ADAMW"
  WARMUP_ITERS: 1500
  BASE_LR: 0.0001
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 0
  WEIGHT_DECAY: 0.05
  LR_SCHEDULER_NAME: "WarmupPolyLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0